function output = default_output(opt)
  % (C) Copyright 2022 Remi Gau
  output = struct('png', true, ...
                  'csv', false, ...
                  'threshSpm', false, ...
                  'binary', false, ...
                  'nidm', false);
  output.montage.do = true();
  output.montage.slices = -27:3:58; % in mm
  output.montage.orientation = 'axial';
  output.montage.background = ...
      spm_select('FPList', ...
                 fullfile(opt.dir.stats, 'derivatives', 'bidspm-groupStats'), ...
                 '.*desc-maskedMean_T1w.nii');
end
