% (C) Copyright 2019 Remi Gau

clear;
clc;

run ../../initEnv.m;

opt = opt_stats_subject_level();

cpp_spm(opt.dir.raw, opt.dir.derivatives, 'subject', ...
        'action', 'results', ...
        'preproc_dir', opt.dir.preproc, ...
        'model_file', opt.model.file, ...
        'fwhm', 6, ...
        'verbosity', 2, ...
        'options', opt);
