% (C) Copyright 2021 Remi Gau

close all;
clear;
clc;

run ../../initEnv.m;

opt = opt_stats_subject_level();

opt.glm.roibased.do = true;
opt.fwhm.func =  0;

opt.space = {'MNI'};

opt.subjects = '.*01';

opt.roi.name = {['^space-.*(', ...
                 strjoin({'V1', ...
                          'V2', ...
                          'V3', ...
                          'hV4', ...
                          'hMT', ...
                          'MST', ...
                          'VO1', ...
                          'VO2', ...
                          'LO2', ...
                          'LO1', ...
                          'neurosynthOlfactory', ...
                          'neurosynthAuditory', ...
                          'neurosyntHand'}, '|') ')']};

% to check
roiList = getROIs(opt);

opt.verbosity = 1;

bidsFFX('specify', opt);
bidsRoiBasedGLM(opt);
