content = bids.util.tsvread(fullfile(pwd, 'sub-blnd01_task-olfid_run-01_events.tsv'));

transformer = struct('Name', 'Add', ...
  'Input', 'onset', ...
  'Query', 'trial_type==olf.*', ...  
  'Value', 0.25);

new_content = bids.transformers(transformer, content);

bids.util.tsvwrite(fullfile(pwd, 'sub-blnd01_task-olfid_run-01_desc-new_events.tsv'), ...
  new_content);